spring:
  application:
    name: okten-java-springboot

  profiles:
    active: store1

  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@cluster0.azzfu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "maintenance-base"