spring:
  application:
    name: okten-java-springboot

reference-data:
  engineTypes: Бензиновий, Дизельний, Гібридний
  fuels:
    - name: Дизель
      types: Зимовий, Літній, Арктичний
    - name: Бензин
      types: А-95, А-98, А-100
    - name: Електрика
      types: